---
title: "Homework 8 -- Intro to Probability and Statistics"
author: "Your name here"
output: pdf_document
---

# Instructions:

**Due:** 06/04 at 11:59PM.

**What am I expecting?** An R Markdown with the answers. Note: this one can be done in paper and pencil. If you want to do so, do the problem and take pictures of it. Put the images in a PDF and send it.

**Have fun!**

# Question 1

A factory produces valves, with a 20\% chance of a given valve be broken. The valves are sold in boxes containing ten valves in each box. If no broken valve is found, then they sell the box for \$10.00. With one broken valve, the box costs \$8.00. With two or three, the box is sold for \$6.00. More than three valves broken; they sell the box for \$2.00. What is the mean sales price for the boxes?

# Question 2

If a random variable $X$ has distribution:

|   x  |  -2 |  -1  |  0  |   1  |   2  |
|:----:|:---:|:----:|:---:|:----:|:----:|
| f(x) | 1/2 | 1/10 | 1/5 | 1/10 | 1/10 |
| F(x) | 1/2 |  3/5 | 4/5 | 9/10 |   1  |

Compute the mean, the variance, and the standard deviation of $X$.

* $X^2$?
* $3X$?

# Question 3

If a random variable $X$ has distribution (note: it is the same as in the previous problem):

|   x  |  -2 |  -1  |  0  |   1  |   2  |
|:----:|:---:|:----:|:---:|:----:|:----:|
| f(x) | 1/2 | 1/10 | 1/5 | 1/10 | 1/10 |
| F(x) | 1/2 |  3/5 | 4/5 | 9/10 |   1  |

Compute the distribution of the following transformations:

* $X^2$?
* $3X$?

# Question 4

Prove the following statements:

* Let two constants, $a \in \mathbb{R}$ and $b \in \mathbb{R}$, and a discrete random variable $X$. Prove that $\mathbb{E}(aX+b) = a\mathbb{E}(X) + b$.

* Let two constants, $a \in \mathbb{R}$ and $b \in \mathbb{R}$, and a discrete random variable $X$. Prove that $\mathbb{V}(aX+b) = a^2\mathbb{V}(X)$.

* Let $a \in \mathbb{R}$ a constant. Prove that $\mathbb{E}(a) = a$ and that $\mathbb{V}(a) = 0$.